export const REPORT_CONCERN = 'REPORT_CONCERN';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const GET_CONCERNS = 'GET_CONCERNS';

export const GET_BARANGAYS = 'GET_BARANGAYS';
export const GET_CONCERN_TYPES = 'GET_CONCERN_TYPES';

export const GET_LESSONS = 'GET_LESSONS';
export const SIGN_IN = 'SIGN_IN';

export const TOKEN = 'TOKEN';
export const USER_INFO = 'USER_INFO';

export const CHECK_IF_LOCATING = 'CHECK_IF_LOCATING';
export const CHECK_IF_DISASTER_IS_ON = 'CHECK_IF_DISASTER_IS_ON';
export const START_LOCATING = 'START_LOCATING';
export const STOP_LOCATING = 'STOP_LOCATING';
